// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateStudentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentRequest) Reset()         { *m = CreateStudentRequest{} }
func (m *CreateStudentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStudentRequest) ProtoMessage()    {}
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{1}
}

func (m *CreateStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentRequest.Unmarshal(m, b)
}
func (m *CreateStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentRequest.Marshal(b, m, deterministic)
}
func (m *CreateStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentRequest.Merge(m, src)
}
func (m *CreateStudentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStudentRequest.Size(m)
}
func (m *CreateStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentRequest proto.InternalMessageInfo

func (m *CreateStudentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateStudentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentResponse) Reset()         { *m = CreateStudentResponse{} }
func (m *CreateStudentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStudentResponse) ProtoMessage()    {}
func (*CreateStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{2}
}

func (m *CreateStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentResponse.Unmarshal(m, b)
}
func (m *CreateStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentResponse.Marshal(b, m, deterministic)
}
func (m *CreateStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentResponse.Merge(m, src)
}
func (m *CreateStudentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStudentResponse.Size(m)
}
func (m *CreateStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentResponse proto.InternalMessageInfo

func (m *CreateStudentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateStudentResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "grpc_poc.Student")
	proto.RegisterType((*CreateStudentRequest)(nil), "grpc_poc.CreateStudentRequest")
	proto.RegisterType((*CreateStudentResponse)(nil), "grpc_poc.CreateStudentResponse")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00) }

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2f, 0x2a, 0x48, 0x8e,
	0x2f, 0xc8, 0x4f, 0x56, 0xd2, 0xe5, 0x62, 0x0f, 0x86, 0x48, 0x09, 0x09, 0x71, 0xb1, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x4c, 0x60, 0x11, 0xa6, 0xcc, 0x14, 0x25, 0x2d, 0x2e, 0x11, 0xe7, 0xa2, 0xd4, 0xc4,
	0x92, 0x54, 0xa8, 0xa6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0x62, 0xac, 0x7a, 0x95, 0xac, 0xb9, 0x44,
	0xd1, 0xd4, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xc3, 0x0c, 0x65, 0x84, 0x19, 0x0a, 0xd7, 0xcc, 0x84,
	0xd0, 0x6c, 0x94, 0xc2, 0xc5, 0x07, 0xd5, 0x16, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x14,
	0xc4, 0xc5, 0x8b, 0x62, 0x9c, 0x90, 0x9c, 0x1e, 0xcc, 0x17, 0x7a, 0xd8, 0xdc, 0x24, 0x25, 0x8f,
	0x53, 0x1e, 0xe2, 0x0e, 0x25, 0x06, 0x27, 0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0x70, 0xa0,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x09, 0x39, 0xfd, 0xd8, 0x25, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateStudentResponse, error)
}

type studentServiceClient struct {
	cc *grpc.ClientConn
}

func NewStudentServiceClient(cc *grpc.ClientConn) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateStudentResponse, error) {
	out := new(CreateStudentResponse)
	err := c.cc.Invoke(ctx, "/grpc_poc.StudentService/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	CreateStudent(context.Context, *CreateStudentRequest) (*CreateStudentResponse, error)
}

// UnimplementedStudentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (*UnimplementedStudentServiceServer) CreateStudent(ctx context.Context, req *CreateStudentRequest) (*CreateStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudent not implemented")
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_poc.StudentService/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).CreateStudent(ctx, req.(*CreateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_poc.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudent",
			Handler:    _StudentService_CreateStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}
